

import Foundation
public struct ConfigModel: Codable {
    public let stepId: Int
    public let tenantIdentifier: String
    public let blockIdentifier: String
    public var instanceId: String
    public let applicationId: String
    public var flowInstanceId: String
    public let flowIdentifier: String
    public let instanceHash: String
    public let flowName: String
    public let stepDefinitions: [StepDefinitions]
    public let stepMap: [StepMap]

}
public struct StepDefinitions: Codable {
    public  let stepId: Int
    public  let stepDefinition: String
    public  let customization: Customization
    public  let mappings: [TokensMappings]?
    public  let outputProperties: [OutputProperties]
    public  let inputProperties: [InputProperty]
}

public struct StepMap: Codable {
    public let id: Int
    public let stepType: Int
    public let stepName: String
    public let stepDefinition: String
    public let parentStepId: Int?
    public let numberOfBranches: Int?
    public let isVirtual: Bool
    public let  branches: [[StepMap]]?
}



public struct OutputProperties: Codable {
    public let id: Int
    public let key: String
    public let keyIdentifier: String?
    public  let displayName: String
    public  let isRequired: Bool?
    public let isExcluded: Bool?
    public  let type: Int?
}


public struct StepTypeDto: Codable {
    var id: Int
}

public struct Customization: Codable {
    public let header: String?
    public let subHeader: String?
    public let svgLogoUrl: String?
    public let file: String?
    public let nextButtonTitle: String?
    public let processMrz: Bool?
    public let confirmationRequired: Bool?
    public let showResultPage: Bool?
    public let documentLiveness: Bool?
    public let storeCapturedDocument: Bool?
    public let performLivenessDetection: Bool?
    public let stepTypeDto: StepTypeDto
    public let storeImageStream: Bool?
    public let saveCapturedVideo: Bool?
    public let outputProperties: [OutputProperties]
    public let identificationDocuments: [IdentificationDocuments]?
    public let branches: [Branch]?
    public let allowAssistedDataEntry: Bool?
    public let assistedDataEntryPages: [AssistedDataEntryPage]?
    public let inputProperties: [InputProperty]?
    public let selectedTemplates: [Int]?
    public let confirmationMessage: String?
    public let autoDownload: Bool?
    public let enableDigitalSignature: Bool?
    public let hideSignatureBoard: Bool?
    public let otpInputType: Int?
    public let enableOtp: Bool?
    public let otpSize: Int?
    public let otpType: Int?
    public let otpExpiryTime: Double?
    public  var otpTargets: [String]? = []
    public  var autoGeneratedSignatureValues:[String]? = []
    public  var enableSignatureVisualVerifier:Bool?
    public  var faceImageSource:String?
    public  var isNormalClick:Bool?
    public let otpFormat: Int?
    public let smsProvider: Int?
    public let whatsappProvider: Int?
    
}

public struct Branch: Codable {
    public  let branchIndex: Int
    public let conditions: [Condition]
}

public struct Condition: Codable {

    public let label: String?
    public let inputPropertyKey: String
    public let conditionOperator: Int?   // 1 AND, 2 OR
    public let `operator`: Int           // backticks because "operator" is reserved in Swift
    public let useAge: Bool?
    public let value: String?

}


public struct InputProperty: Codable {
    
    public let id: Int
    public let sourcePropertyId: Int
    public let sourceStepId: Int
    public let sourceKey: String
    public let targetPropertyId: Int
    public let targetStepId: Int
    public let targetKey: String
    public let isDeleted: Bool
    
    public init(
        id: Int,
        sourcePropertyId: Int,
        sourceStepId: Int,
        sourceKey: String,
        targetPropertyId: Int,
        targetStepId: Int,
        targetKey: String,
        isDeleted: Bool
    ) {
        self.id = id
        self.sourcePropertyId = sourcePropertyId
        self.sourceStepId = sourceStepId
        self.sourceKey = sourceKey
        self.targetPropertyId = targetPropertyId
        self.targetStepId = targetStepId
        self.targetKey = targetKey
        self.isDeleted = isDeleted
    }
}





public struct IdentificationDocuments: Codable {
    public let key: String?
    public let enabled: Bool?
    public let documentType: Int?
    public let selectedCountries: [String]?
    public let supportedIdCards: [String]?

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        key = try container.decodeIfPresent(String.self, forKey: .key)
        enabled = try container.decodeIfPresent(Bool.self, forKey: .enabled)
        documentType = try container.decodeIfPresent(Int.self, forKey: .documentType)
        supportedIdCards = try container.decodeIfPresent([String].self, forKey: .supportedIdCards)

        if let rawCountries = try? container.decodeIfPresent([String?].self, forKey: .selectedCountries) {
            selectedCountries = rawCountries.compactMap { $0 }
        } else {
            selectedCountries = nil
        }
    }
}

public enum IdentificationDocumentsDocumentType {
    public static let Passport = 1
    public static let ID = 2
}


public func encodeStepDefinitionsToJson(data: [StepDefinitions]) -> String {
    let encoder = JSONEncoder()
    do {
        let jsonData = try encoder.encode(data)
        return String(data: jsonData, encoding: .utf8) ?? ""
    } catch {
        return "\(error.localizedDescription)"
    }
}
