

import Foundation

public struct DataModel: Codable {
    public  let selectedTemplates: [Int]
    public  let header:String?
    public  let subHeader:String?
    public  let svgLogoUrl:String?
    public  let confirmationMessage:String?
    public  let autoDownload:Bool
    public  let enableDigitalSignature:Bool
    public  let hideSignatureBoard:Bool?
    public  let otpInputType:Int?
    public  let enableOtp:Bool
    public  let otpSize:Int?
    public  let otpExpiryTime:Double?
    public  var otpTargets: [String] = []
    public  var autoGeneratedSignatureValues:[String] = []
    public  var enableSignatureVisualVerifier:Bool?
    public  var faceImageSource:String?
    public  var isNormalClick:Bool
    public var otpFormat: Int?
    public var smsProvider: Int?
    public var whatsappProvider: Int?
    
}



public struct ContextAwareSigningModel: Codable {
    public  let statusCode: Int
    public  let data: DataModel
}
